name: Keep Render Alive

on:
  schedule:
    - cron: "*/10 * * * *"  # every 10 minutes
  workflow_dispatch:        # allows you to run it manually

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render API
        id: ping
        run: |
          response=$(curl -s -w "\n%{http_code}" https://athichudi-api.onrender.com/health)
          http_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | head -n1)
          echo "status=$http_code"
